# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5d34048616a7dc8e5bb7ee318857d18c854e9698f30681605abe62f3242dce8c12e22012e7a18901ee41adc02d7dac53bbd821c55a76b66b47d8a19a1c3770f

test:
  secret_key_base: ce42fb67b5b15594f6976e47acb06bf612350e33507b1faa3013c2074d989337638c11070b3b1eedc65417da3cd242749f39b5f8c43109cab7e9d78ce01aca53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
